export const stackIcons: { [key: string]: string } = {
  react: '/assets/icon/react.svg',
  reactnative: '/assets/icon/reactnative.svg',
  typescript: '/assets/icon/typescript.svg',
  javascript: '/assets/icon/javascript.svg',
  styledcomponent: '/assets/icon/styledcomponent.svg',
  reactquery: '/assets/icon/reactquery.svg',
  redux: '/assets/icon/redux.svg',
  recoil: '/assets/icon/more.svg',
  github: '/assets/icon/github.svg',
  tailwind: '/assets/icon/tailwind.svg',
  axios: '/assets/icon/axios.svg',
  webpack: '/assets/icon/webpack.svg',
  swift: '/assets/icon/swift.svg',
  nextjs: '/assets/icon/next-js.svg',
  zeplin: '/assets/icon/zeplin.svg',
}
